package-lock.json
package.json
src/github.js
src/google.js
src/onedrive.js
test/post-deploy.js

Post deploy tests

---

package-lock.json
package.json
src/cache.js
src/github.js
src/index.js
test/cache.test.js
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-Word_3165599571/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Missing-Document-from-Word_3222296563/recording.har
test/github.test.js
test/index.test.js
test/onedrive.test.js

This PR adds a simple memoization function based on a LRU cache that remembers the FSTabs for the last 1000 repo, owner, ref pairs.

Cache fstab fetching

---

src/index.js
test/post-deploy.js

see https://dashboard.epsagon.com/search/?search_filters%5B0%5D%5Bfilter%5D=resource_name&search_filters%5B0%5D%5Bop%5D=%3D&search_filters%5B0%5D%5Bvalue%5D=content-proxy&search_filters%5B1%5D%5Bfilter%5D=error&search_filters%5B1%5D%5Bop%5D=%3D&search_filters%5B1%5D%5Bvalue%5D=true&search_filters%5B2%5D%5Bfilter%5D=exception.type&search_filters%5B2%5D%5Bop%5D=%3D&search_filters%5B2%5D%5Bvalue%5D=TypeError&time_frame%5Btype%5D=custom&time_frame%5Bfrom%5D=1590396335169&time_frame%5Bto%5D=1590569135169&time_frame%5Bfrequency%5D=86400 for example occurences

fix(index): prevent crashing from undefined errors

---

package-lock.json
package.json
src/excel-json.js
test/excel-json.test.js

Excel json support

---

src/excel-json.js
src/google-json.js
src/google.js
src/index.js
src/onedrive.js
test/fixtures/Google-Integration-Tests_1198572065/Retrieves-Document-from-Google-Docs_2178742967/recording.har
test/fixtures/Google-Integration-Tests_1198572065/Retrieves-Missing-Document-from-Google-Docs_368393367/recording.har
test/index.test.js

fix(index): use customer namespace

---

src/index.js

fix(index): wait for handler to complete to catch async errors

---

src/excel-json.js
test/post-deploy.js

Qb pagination fix

---

src/index.js
test/index.test.js
test/post-deploy.js

feat(json): enable all querybuilder parameters

---

src/excel-json.js
src/github.js
src/google-json.js
src/google.js
src/onedrive.js

Surrogate for url

---

src/excel-json.js
test/excel-json.test.js

fix(excel): use correct source-location

---

src/google-json.js
test/fixtures/Google-JSON-Tests_2094740521/gets-sheet-by-id-from-google_1101452622/recording.har
test/google.test.js

related to #72 
avoid caching until we find a better way to disable it during local developmemnt.

fix(google): disable caching for google sheets

---

src/excel-json.js
test/excel-json.test.js

feat(excel): use onedrive uri

---

.eslintignore
package.json
src/excel-json.js
src/github.js
src/google-json.js
src/google.js
src/index.js
src/onedrive.js
src/utils.js
test/excel-json.test.js
test/fixtures/Excel-JSON-Integration-tests_3656940029/Get-JSON_3236052051/recording.har
test/utils.test.js

feat: consolidate helix fetch changes and disable caching

---

src/google-json.js
test/google.test.js

feat(google): fix source-location

---

src/onedrive.js
test/fixtures/Google-Integration-Tests_1198572065/Retrieves-Document-mounted-md-from-Google-Docs_898325242/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-mounted-md-from-Word_2825340960/recording.har
test/google.test.js
test/onedrive.test.js

fixes #97
- needs: https://github.com/adobe/helix-shared/pull/343

feat(fstab): support mounting of documents

---

.gitignore
src/google-helpers.js
src/google-json.js
src/google-reverse.js
src/index.js
src/onedrive-reverse.js
src/reverse.js
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-404-for-google-document-no-fstab-_2300778801/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-404-for-google-document-no-matching-mountpoint-_206813439/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-redirect-for-google-document-custom-prefix-_1259289871/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-redirect-for-google-document-gdrive-uri-_2605905885/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-redirect-for-google-document-main-branch-_1125013453/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-redirect-for-google-document-non-default-branch-_924736816/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-redirect-for-google-document_1127208019/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-redirect-for-google-sheet_3254950425/recording.har
test/google-reverse.test.js
test/google.test.js
test/index.test.js
test/onedrive-reverse.test.js

Reverse lookup

---

src/github.js
src/google-json.js
src/index.js
src/utils.js
test/google.test.js

fix(fetch): improve timeout and google error handling

---

src/index.js
test/index.test.js

fix(index): return 400 on invalid path

---

src/filename-to-url.js
src/onedrive-reverse.js
src/onedrive.js
test/filename-to-url.test.js
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-Word_3165599571/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-mounted-md-from-Word_2825340960/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Missing-Document-from-Word_3222296563/recording.har
test/onedrive-reverse.test.js
test/onedrive.test.js

fixes #168
- resolves word documents with author-friendly names correctly
- uses word2md V2

fix(resolve): respect author friendly url mapping and use word2md V2

---

.github/workflows/wip.yaml
src/excel-json.js
src/google-json.js
src/google.js
src/index.js
src/onedrive.js
src/utils.js
test/excel-json.test.js
test/index.test.js

needs: https://github.com/adobe/openwhisk-action-utils/pull/110

feat(ci): make use of ow-version-lock utility

---

src/index.js
test/index.test.js

fix(json): forward sheet and table params to data-embed

---

src/google-reverse.js
test/google-reverse.test.js

fix(reverse): google drive reverse lookup not sanitized

---

src/index.js
src/vary.js
test/github.test.js
test/google.test.js
test/index.test.js
test/onedrive.test.js
test/vary.test.js

feat(caching): add x-ow-version-lock to vary response header

---

src/google-helpers.js
src/google-reverse.js
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-404-for-not-existent-google-document_259312938/recording.har
test/google-reverse.test.js

fix(lookup): catch gaxios errors

---

src/onedrive-edit-link.js
test/onedrive-edit-url.test.js

fix(edit): fix edit link for md

---

src/onedrive-json.js
test/fixtures/Excel-JSON-Integration-tests_3656940029/Get-JSON-on-author-friendly-url_1940273107/recording.har
test/index.test.js
test/onedrive-json.test.js
test/onedrive-reverse.test.js

fix(json): respect author friendly transformation for json (onedrive)

---

src/github.js
src/index.js
test/fixtures/GitHub-Integration-Tests_1546263629/Retrieves-Markdown-from-mounted-GitHub-repo-using-FSTab-yaml-is-present_2992715442/recording.har
test/github.test.js

feat(github): add support for mounting github repos

---

src/onedrive-reverse.js
test/dev/index.js
test/onedrive-reverse.test.js

fix(reverse): fix lookup problems with url with no edit mode markers

---

package-lock.json
package.json
src/lookup-edit-url.js
test/onedrive-edit-url.test.js
test/post-deploy-utils.js
test/post-deploy.js
test/utils.js

fix(edit): edit lookup fails with 500 for non existent sharelink

---

src/google-reverse.js
src/onedrive-reverse.js
src/reverse.js
test/google-reverse.test.js
test/onedrive-reverse.test.js

feat(lookup): omit .html extension (#285)

---

package-lock.json
package.json
src/utils.js
test/onedrive-json.test.js

fix(deps): bump helix-fetch and re-enable http/2

---

src/github.js
test/fixtures/GitHub-Integration-Tests_1546263629/Retrieves-Markdown-from-mounted-GitHub-repo-using-FSTab-yaml-is-present_2992715442/recording.har

feat(github): only resolve ref if unknown

---

src/onedrive-reverse.js
test/onedrive-reverse.test.js

see https://github.com/adobe/helix-pages/issues/706

fix(revers): handle more sharelink variants

---

src/onedrive.js
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-Word_3165599571/recording.har

Relates to https://github.com/adobe/helix-word2md/pull/564

fix(onedrive): pass last-modified from word2md

---

src/index.js

fix: return 504 on ECONNRESET

---

src/github.js
src/google-sitemap.js
src/index.js
src/onedrive-sitemap.js
test/google-sitemap.test.js
test/onedrive-sitemap.test.js
test/post-deploy.js

fix(sitemap): send sitemap with application/xml

---

package-lock.json
src/index.js
src/lookup-edit-url.js
src/utils.js
test/fixtures/Google-Edit-Link-Tests_677788119/Returns-redirect-for-google-based-page-html-lnk-_3076794425/recording.har
test/fixtures/Google-Edit-Link-Tests_677788119/Returns-redirect-for-google-based-page-lnk-_2825033822/recording.har
test/fixtures/Google-Edit-Link-Tests_677788119/Returns-redirect-for-google-based-spreadsheet-lnk-_2515479485/recording.har
test/fixtures/Google-Reverse-Lookup-Tests_3892420431/Returns-redirect-for-google-document-base64-_1580075095/recording.har
test/github-edit-url.test.js
test/google-edit-url.test.js
test/google-reverse.test.js
test/onedrive-edit-url.test.js
test/onedrive-reverse.test.js
test/post-deploy.js

feat(lookup): add support for lnk

---

package-lock.json
src/github.js
src/google-json.js
src/google-sitemap.js
src/google.js
src/index.js
src/lookup-edit-url.js
src/onedrive-json.js
src/onedrive-sitemap.js
src/onedrive.js
src/reverse.js
src/utils.js
test/google.test.js
test/onedrive-edit-url.test.js
test/onedrive.test.js

fixes https://github.com/adobe/project-helix/issues/536
https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@ci1739?owner=adobe&repo=spark-website&ref=main&path=/&edit=%3Cscript%3Ealert(document.domain)%3C/script%3E

fix(error): use text/plain to report errors

---

src/google.js
src/onedrive.js
test/post-deploy.js

fix(md): use correct content-type

---

package-lock.json
package.json
src/utils.js

fix(utils): ensure x-error header value is clean

---

src/index.d.ts
src/index.js
src/lookup-edit-url.js
test/onedrive-edit-url.test.js

feat(lookup): add support for reports

---

src/index.d.ts
src/index.js
src/reverse.js
test/dev/index.js
test/onedrive-reverse.test.js

feat(reverse): add cors headers for well known origins

---

src/google-json.js
src/onedrive-json.js
test/fixtures/Excel-JSON-Integration-tests_3656940029/Get-JSON-on-author-friendly-url_1940273107/recording.har
test/fixtures/Excel-JSON-Integration-tests_3656940029/Get-JSON_3236052051/recording.har
test/fixtures/Google-JSON-Tests_2094740521/gets-sheet-by-id-from-google_1101452622/recording.har
test/index.test.js
test/onedrive-json.test.js

fix(json): use data-embed v3

---

package-lock.json
src/google.js
src/onedrive.js
test/fixtures/Google-Integration-Tests_1198572065/Retrieves-Document-from-Google-Docs_2178742967/recording.har
test/fixtures/Google-Integration-Tests_1198572065/Retrieves-Document-mounted-md-from-Google-Docs_898325242/recording.har
test/fixtures/Google-Integration-Tests_1198572065/Retrieves-Missing-Document-from-Google-Docs_368393367/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-Word-with-If-Modified-Since_2396489111/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-Word_3165599571/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-a-private-repository-with-credentials_809520207/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-a-private-repository-with-unknown-credentials_1980587233/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-from-a-private-repository-with-user-credentials_1569403714/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Document-mounted-md-from-Word_2825340960/recording.har
test/fixtures/OneDrive-Integration-Tests_690026202/Retrieves-Missing-Document-from-Word_3222296563/recording.har
test/onedrive.test.js

fix: use word2md and gdocs2md V3
